name: Container Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc5, gcc10, clang39, clang10]
    runs-on: [self-hosted, docker]
    container:
      image: conanio/${{ matrix.compiler }}
      options: --user 0:0
      volumes:
        - /home/buildbot/.ssh:/github/home/.ssh
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: INFO
        run: echo $HOME
      - name: INFO
        run: id
      - name: INFO
        run: ls ~/.ssh
      - name: INFO
        run: ls -la ~/.ssh
      - name: install ssh
        run: apt update
      - name: install ssh
        run: apt -y install openssh-client
      - name: github ssh check
        run: ssh -T git@github.com
      - name: Configure
        run: python3 waf configure --git_protocol=git@
      - name: Build
        run: |
          echo "::add-matcher::.github/gcc-problem-matcher.json"
          python3 waf
      - name: Test
        run: python3 waf --run_tests
      - name: Status
        run: echo "Build ${{ job.status }}"