name: Container Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc5, gcc10, clang39, clang10]
    runs-on: [self-hosted, docker]
    container:
      image: conanio/${{ matrix.compiler }}
      options: --user 0:0
      volumes:
        - /home/buildbot/.ssh:/root/.ssh
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: INFO
        run: echo $HOME
      - name: INFO
        run: id
      - name: install ssh
        run: apt update
      - name: install ssh
        run: apt -y install openssh-client
      - name: INFO
        continue-on-error: true
        run: ls /etc/ssh/ssh_config
      - name: ssh start agent
        continue-on-error: true
        run: eval "$(ssh-agent -s)" && ssh-add /root/.ssh/id_ed25519 && ssh -T git@github.com
      - name: github ssh check
        continue-on-error: true
        run: ssh -T git@github.com
      - name: Configure
        run: python3 waf configure --git_protocol=git@
      - name: Build
        run: |
          echo "::add-matcher::.github/gcc-problem-matcher.json"
          python3 waf
      - name: Test
        run: python3 waf --run_tests
      - name: Status
        run: echo "Build ${{ job.status }}"