name: Cppcheck
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # 3 AM CET
  push:
jobs:
  docker_check:
    name: Cppcheck 2.4.1
    uses: steinwurf/cppcheck-action/.github/workflows/action.yml@v1