name: C++ make-specs Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - cxx_mkspec: cxx_msvc16_x86,
          name: MSVC 16 32-bit
        - cxx_mkspec: cxx_msvc16_x64,
          name: MSVC 16 64-bit
        - cxx_mkspec: cxx_apple_llvm120_x64
          name: Apple LLVM 12.0 64-bit
    runs-on: [self-hosted, '${{ matrix.cxx_mkspec }}']
    name: ${{ matrix.config.name }}
    steps:
      - name: Set python env variable
        run: echo "python=python3" >> $GITHUB_ENV
      - name: Rename python3 to python
        if: runner.os == 'Windows'
        run: echo "python=python" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: ${{ env.python }} waf configure --git_protocol=git@ --cxx_mkspec=${{ matrix.cxx_mkspec }}
      - name: Build
        run: |
          echo "::add-matcher::.github/gcc-problem-matcher.json"
          ${{ env.python }} waf
      - name: Test
        run: ${{ env.python }} waf --run_tests
